### ISSUE TITLE
Theme Error

### ISSUE THREAD

**Issue by btd1337** [gusbemacbe/suru-plus-telinkrin#4]
* **Distribution and version:**
Arch Linux
* **Distribution environment:**
  - [ ] Cinammon
  - [x] Gnome
  - [ ] KDE
  - [ ] LXDE
  - [ ] MATE
  - [ ] XCFE
  - [ ] Other. Name here: 

Many icons are not loading without Suru++! It's necessary to add its as dependency before installation!

![screenshot from 2018-06-10 23-46-33](https://user-images.githubusercontent.com/11943860/41210560-f2e6ca7e-6d08-11e8-9a6b-db713b572e3e.png)

![untitled](https://user-images.githubusercontent.com/11943860/41210685-8a64aeca-6d09-11e8-9533-d438934a86ba.png)

**Comment by gusbemacbe** [comment]
Hello Helder!

Did you use the last version of Suru++ Telinkrin?

The old versions of Suru++ Telinkrin used symlinks which depended on the [Suru++](https://github.com/gusbemacbe/suru-plus) icons theme. 

In the last version of Suru++ Telinkrin, I purged the symlinks and replaced for the native and original icons, for not depending any more on other icons themes.

**Comment by btd1337** [comment]
Yes, I has installed via cli yesterday.

**Comment by gusbemacbe** [comment]
Hello Helder,

After college holidays, I will test and analyse it on Arch Linux virtual machine, although I be a Manjaro user. 

Please see if [Suru++](https://github.com/gusbemacbe/suru-plus) have the same problems in Arch Linux.

**Comment by btd1337** [comment]
No, He have not.

Apparently, modify was not commited.

**Comment by gusbemacbe** [comment]
Sorry, Helder, but I did not understand yet. Let's write in Portuguese.

Eu perguntei se Suru++ de Andrea Bonanni tem ainda o mesmo problema no Arch Linux e tu disseste que não tem. Certo?

**Comment by gusbemacbe** [comment]
🇬🇧 I installed Arch Linux, analysed and investigated the cause of icons error in Suru++ Telinkrin, I discovered that there are still symlink zombies that I failed to purge in the package. I have to purge the zombies again to end bug in the next version after the college holidays. I also understood that not only you, it also affected @bzhmurov, then the missed icons on his GNOME Control Centre were caused by symlink zombies that I failed to purge in the last version.
🇧🇷 Instalei o Arch Linux, analisei e investiguei a causa de erro de ícones no Suru++ Telinkrin, descobri que há ainda symlinks zumbis que falhei em exterminar no pacote. Tenho de exterminar os zumbis novamente para pôr fim aos bugs na próxima versão beta após as férias da faculdade. Tamb´ḿ entendi que não só tu, também @bzhmurov, então os ícones perdidos no Centro de Controlo de GNOME eram causados pelos symlinks zumbis que falhei em exterminar na última versão.

**Comment by btd1337** [comment]
Great. I'm waiting the release of new version.

**Comment by gusbemacbe** [comment]
It has already been released before. I called you in another issue.

**Comment by gusbemacbe** [comment]
#5
